# Basic site info
title: "Ryan Lazar"
description: "Business Analyst & Aspiring Data Engineer"
url: "https://LazarRyan.github.io" # Use your GitHub Pages URL
baseurl: "" # Keep this empty for user/organization sites

# Theme
theme: cayman

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author info
author:
  name: "Ryan Lazar"
  email: "Lazar.Ryan123@gmail.com"
