theme: minimal-mistakes-jekyll

plugins:
  - jekyll-remote-theme

remote_theme: mmistakes/minimal-mistakes@4.24.0
title: Ryan Lazar's Portfolio
description: A showcase of my projects in data, analytics, and engineering.
