title: "Ryan Lazar"
description: "Business Analyst & Data Engineer Portfolio"
baseurl: ""
url: "https://LazarRyan.github.io"

theme: minimal-mistakes-jekyll

remote_theme: mmistakes/minimal-mistakes@4.24.0

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

author:
  name: "Ryan Lazar"
