# Basic site info
title: "Ryan Lazar"
description: "Business Analyst & Aspiring Data Engineer"
url: "https://LazarRyan.github.io"
baseurl: ""

# Theme setup
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Required plugins for GitHub Pages + Minimal Mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Author info
author:
  name: "Ryan Lazar"
  avatar: "avatar.jpg"
  bio: "Python | SQL | Business Analytics | M.S. in Data Science"

# Top navigation bar
nav:
  - title: About
    url: /about/
  - title: Projects
    url: /projects/
  - title: Resume
    url: /resume/
